name: Product service application workflow
on:
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - '.github/workflows/product-service-workflow.yaml'
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - '.github/workflows/product-service-workflow.yaml'

jobs:
  project-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up the Maven dependencies caching
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install Maven dependencies and build
        run: mvn clean install

      - name: Run tests
        run: mvn --batch-mode --update-snapshots verify